# Generated by Django 3.1.3 on 2020-11-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='articul',
            new_name='articule',
        ),
    ]
